### ISSUE TITLE
Search bar is not usable

### ISSUE THREAD

**Issue by J-bytes** [asc-csa/Scisat-App#10]
The canada search bar cannot be used. Clicking on it simpy does an empty search but it at least links to a page that allows that search

![image](https://user-images.githubusercontent.com/60334318/99288766-1ad6c980-280a-11eb-9e55-b3b6138ec782.png)

![image](https://user-images.githubusercontent.com/60334318/99288796-22966e00-280a-11eb-9bb7-10b6e8370a2e.png)

**Comment by emilinecsa** [comment]
The search bar works well for both SCISAT & Alouette micro applications. The latest version of the Alouette micro applications was deployed on the production server on April 13th.
