### ISSUE TITLE
Incomplete translation - SCISAT 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#105]
The translation for certain elements seems to have broken when I switched to the new App-Launcher config (ie. 1 app per language). The image below is the French page. 

![image](https://user-images.githubusercontent.com/11013061/115416853-1e5dea80-a1c6-11eb-9dd4-5dc04146a1ce.png)

@coleweusthem - are you having the same issue? 

Edit: WAVE-ing the page, seems that the language is still EN. Might be an issue with how I configured it locally but it's strange that it's still translating certain things. 
![image](https://user-images.githubusercontent.com/11013061/115417772-e7d49f80-a1c6-11eb-9e82-e3edab792e00.png)

**Comment by coleweusthem** [comment]
<img width="1185" alt="Screen Shot 2021-04-20 at 11 56 05 AM" src="https://user-images.githubusercontent.com/46227765/115418009-7fd68700-a1cf-11eb-82cf-c2d2895be01f.png">

Looks mostly correct on mine, the learn more button is wrong, and maybe the header

**Comment by coleweusthem** [comment]
<img width="1193" alt="Screen Shot 2021-04-20 at 12 00 16 PM" src="https://user-images.githubusercontent.com/46227765/115418582-fa9fa200-a1cf-11eb-978e-f058f1766924.png">

**Comment by nfee006** [comment]
Ok - for context I'm on branch comms-24.

**Comment by nfee006** [comment]
Config file

![image](https://user-images.githubusercontent.com/11013061/115451016-a229ce00-a1ea-11eb-8cf7-338cde96bbf9.png)

@coleweusthem in reference to https://github.com/asc-csa/Scisat-App/pull/103

**Comment by coleweusthem** [comment]
try changing APP_PREFIX to the url you are using for the french version. I think it uses that for the callbacks etc.

**Comment by nfee006** [comment]
@coleweusthem that did it, thanks! The issue of the title/read more button remains but I think I saw you address that somewhere.

![image](https://user-images.githubusercontent.com/11013061/115452098-01d4a900-a1ec-11eb-967e-1daa62e83acc.png)

**Comment by nfee006** [comment]
Addressed by fixing local config and #104.
