### ISSUE TITLE
Question: analytics.py

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#107]
@coleweusthem: is it possible to accidentally publish the active analytics.py script with this setup? We'll need something like we have for ckan.

**Comment by coleweusthem** [comment]
I don't think, the only time you'd ever fill in that file is in production, and I doubt you're ever pushing changes from production.

**Comment by nfee006** [comment]
Yeah but we'll still need a failsafe of some variety, just like with ckan.
