### ISSUE TITLE
Graph textual alternative formatting issue

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#112]
Occurs when the window is reduced. 

![image](https://user-images.githubusercontent.com/11013061/116241648-1c021000-a733-11eb-8533-153bccb76b97.png)

**Comment by nfee006** [comment]
@coleweusthem issue still exists after latest merge to master

**Comment by coleweusthem** [comment]
@nfee006, can we let the overflow scroll? the headers are a little long for any other options

**Comment by nfee006** [comment]
I think scroll is fine
