### ISSUE TITLE
Callback system fix 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#116]
@coleweusthem - I'm making this issue so that we can coordinate and minimize merge conflicts.

@dreneuw had made some changes (fixes) to the callback system in https://github.com/asc-csa/Scisat-App/pull/87. Right now it's linked to the sidebar implementation branch (which we don't want to merge right now) so he's going to work on implementing this based on the dev branch. 

Since he's rearranging a fair bit, this is likely going to cause some merge conflicts. How would you prefer for us to proceed? Should we wait until we merge the wet-boew form validator changes? We've got a bit of a time crunch in that he needs to implement the changes before the end of term on Friday.

**Comment by coleweusthem** [comment]
@dreneuw  & @nfee006, I think I've addressed everything in scisat, so if you use #115 that is the most up to date branch.

You'll need to use the new dash-core-components or it'll break
[dash_core_components.tar.gz](https://github.com/asc-csa/Scisat-App/files/6393369/dash_core_components.tar.gz)

**Comment by nfee006** [comment]
@coleweusthem so 117 was based on dev and now 115 so we're running into merge issues with your PR. I wanted to get your input as to how best to proceed. Right now we've merged 117 into dev but we could easily unmerge it. 

Options
1. We tried resolving the conflicts directly into your 114 and 115 branch. This led to some issues because it's only a partial implementation of the callback fix. My concern is that it may not work as expected when we merge and we need to resolve this before the end of term (ie. tomorrow ideally). 
2. We could unmerge 117, let you finish up your edits to 114 and 115 and merge them, and then resolve the conflicts when we merge 117. The time crunch comes into play here though - how long do you think that might take? 
3. Something else that I'm not thinking of. 

What do you think?

**Comment by dreneuw** [comment]
In more details, to me it seems like the most time-sensitive solution would be to revert the few changes I have done to #115, start a new branch based on #115, quickly reimplement the callback fixes that were done in #117, which should take less than an hour and merge that back into #115. This way, when we merge #115 to development, we will not lose any of the callback work done.

**Comment by nfee006** [comment]
@coleweusthem @dreneuw 

I agree with David's comment. Let's do that.

**Comment by coleweusthem** [comment]
@nfee006, @dreneuw, can we hold off for one second. I think I may have gotten the #114 and #115 branches mixed up. apologies

**Comment by coleweusthem** [comment]
@nfee006, @dreneuw, ok, proceed. #115 is the most up-to-date, I had started merging the dev branch into #114 so it looked farther ahead on my local machine

**Comment by nfee006** [comment]
@coleweusthem 

With https://github.com/asc-csa/Scisat-App/pull/118 we're done with those major changes we discussed. Feel free to make any changes you need in SCISAT now. Thanks.
