### ISSUE TITLE
Missing definition of error bars in altitude plot figure caption

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/Scisat-App#124]
The figure caption should indicate the type of error bars.

With further edits of the text:
Graph [Plot] showing the gas concentration in parts per volume (ppv) over the selected altitude interval. The value represents the mean concentration over the selected latitudes, longitudes and dates. Error bars are 95% confidence intervals around the mean.

**Comment by emilinecsa** [comment]
This has not been fixed yet. In addition, I recommend to rename both lat & lon: Latitude & Longitude.
