### ISSUE TITLE
Order of lat lon is important but does not raise a validation flag

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/Scisat-App#129]
The selections are meant to be small value then large value, but inversing this causes an error but without an associated validation flag.
Potential ideal behaviour would be to allow selection that accounts for the fact that the world is a glob, so inverse order would select the other side of the globe.

**Comment by emilinecsa** [comment]
The issue is fixed. - TESTED on production on April 20th, 2023.

The user cannot specify a latitude or longitude value that is not in range. The application shows an error that gives the appropriate range.
