### ISSUE TITLE
Accessibility - Update button span (Comms #2) 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#138]
[Accessibilité]  
The attribute « tabindex » has been added to the span « Update » to make it keyboard accessible. You must use a <button> instead (or move the tabindex to the parent span (#generate) and add the attribute role=button) 
[37]

@coleweusthem FYI

**Comment by nfee006** [comment]
Addressed in prod (see pull requests).

**Comment by nfee006** [comment]
@coleweusthem Feedback from Comms:

The tabindex works in that it allows you to focus on the "Update" span. However, when click "enter" on the keyboard, nothing happens. You can only activate it with a mouse click. We need to be able to use the "enter" button as well.

**Comment by coleweusthem** [comment]
Made a change that should fix it for them

**Comment by nfee006** [comment]
Works for me; I'll run it by comms. Thanks!
