### ISSUE TITLE
Web standards - Top of page bookmark (comms 1)

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#141]
1.    [Standard web]  
There is a "Top of page" link which points towards an inexistant bookmark. The "wb-cont" must be added to the H1 like ID

[36]
`<a href="#wb-cont">Top of the page<span class="glyphicon glyphicon-chevron-up"></span></a>`

**Comment by coleweusthem** [comment]
added that id to the body tage so that it has something to link to

**Comment by emilinecsa** [comment]
@nfee006  "Top of the page" is no longer part of the [application](https://donnees-data.asc-csa.gc.ca:8888/scisat/). Can we close this issue?
