### ISSUE TITLE
Text forms do not resize according to text size

### ISSUE THREAD

**Issue by spourdei** [asc-csa/Scisat-App#16]
Text-based form controls do not resize when visually rendered text is resized up to 200%. This sometimes causes issues for users using assistive technologies. (Success Criterion 1.4.4 Resize text)

**Comment by emilinecsa** [comment]
The latest version of the SCISAT micro applications was deployed on the production server on April 13th. I will close this bug because I can no longer replicate this issue. Text-based form controls now resizes when visually rendered text is resized up or down.
