### ISSUE TITLE
Dynamic data input

### ISSUE THREAD

**Issue by spourdei** [asc-csa/Scisat-App#18]
The apps currently have all datafiles hardcoded into them. For example, they would take in "ACEFTS_L2_V4P0_O3.nc" for O3, this causes issues when new versions of the datasets are released (most recent version as of now is "ACEFTS_L2_V4P1_O3.nc" which is not recognized by the apps. 

Modify this in a way that allows the apps to take in any version of the data no matter its filename.

**Comment by emilinecsa** [comment]
I suggest to add the filenames into a configuration file that is read when the application starts.

**Comment by emilinecsa** [comment]
I deployed the new version on the QA server on March 13, 2024.

**Comment by emilinecsa** [comment]
I deployed the new version on the QA server on March 19, 2024.
