### ISSUE TITLE
Unoptimized Callback system

### ISSUE THREAD

**Issue by dreneuw** [asc-csa/Scisat-App#30]
The current system used for updating figures and elements has some problems in terms of how it manages callbacks. In more details:
1. Currently, input forms generate a callback on every modifications. This can be updated by setting the 'debounce' attribute of input forms to True. This will make it so that a callback will be done only when the form is deselected.
2. When multiple callbacks are done, they dont cancel each other to only keep the most recent ones, meaning that currently from point 1 not being implemented, an additional callback is done everytime one of the form is modified and all callbacks are loaded in order.
3. Currently there are multiple elements (if not all elements) that have independent callbacks even though they have the same inputs. Most of these elements independently load the dataframe. In general, when changing an input form, 4-5 different callbacks are being done.

Currently, the debounce attribute is not set to True and generally, when wanting to input a different range for latitude and longitude, there are approximately 40 callbacks being done, all of which load the dataframe (among other things). With the debounce attribute set to True, we are looking at approximately 15-20 callbacks.

In order to completely fix this issue, two things should be done:
- Do not process input forms modification and instead add a "Generate" button that runs the callbacks.
- Mainline the callback into one function, which loads all necessary input forms as well as the dataframe, and distribute the information in all functions that are currently using callbacks. This mainline function then returns all the generated figures/elements to the frontend.

**Comment by nfee006** [comment]
@dreneuw: should this be closed?

**Comment by dreneuw** [comment]
Yes, closing it.
