### ISSUE TITLE
Comms Issues #15

### ISSUE THREAD

**Issue by coleweusthem** [asc-csa/Scisat-App#47]
The label element may contain at most one button, input, meter, output, progress, select, or textarea descendant.

`<input class="DateInput_input DateInput_input_1" aria-label="S`

**Comment by coleweusthem** [comment]
This element no longer exists, there most have been a change made to replace it

**Comment by nfee006** [comment]
@coleweusthem: is this not potentially it (date selector)?

![image](https://user-images.githubusercontent.com/11013061/113145830-ee41ae00-91fc-11eb-9543-2e365cc232a8.png)

![image](https://user-images.githubusercontent.com/11013061/113145912-05809b80-91fd-11eb-8dd1-e67e248516af.png)

**Comment by coleweusthem** [comment]
I'll have to look again

**Comment by coleweusthem** [comment]
no longer an issue w3 validator finds
