### ISSUE TITLE
Comms Issues #24

### ISSUE THREAD

**Issue by coleweusthem** [asc-csa/Scisat-App#56]
For the date selection, each input must have its own label. The labels can be hidden using the wb-inv class. Inputs [type=text] must bot be inside the label.

**Comment by coleweusthem** [comment]
@nfee006, according to w3 we can use an aria label instead of a label element: https://www.w3.org/WAI/tutorials/forms/labels/#using-aria-label 

Would that be acceptable? the element dash is using supports aria labels, but adding in actual labels is proving to be a challenge.

**Comment by nfee006** [comment]
If it's WCAG-compliant I see no issue. We use aria-labels elsewhere.

**Comment by coleweusthem** [comment]
@nfee006, cool, they are using a react component airbnb created, and I was having trouble modifying it.

**Comment by coleweusthem** [comment]
I've added a solution to this to the new dash fork

**Comment by coleweusthem** [comment]
has been corrected
