### ISSUE TITLE
Broken links to GCWeb theming elements

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#64]
A recent GCWeb update has broken the links to various external theming files (CSS, js, icons, etc..). More details here: https://github.com/wet-boew/GCWeb/issues/1792#issuecomment-797027224

![image](https://user-images.githubusercontent.com/11013061/110853111-35cdbd80-8281-11eb-911c-aa985e8e60d6.png)
![image](https://user-images.githubusercontent.com/11013061/110853141-3e25f880-8281-11eb-901a-3cc2565790b4.png)

From now on, we should aim to store all of these files locally. We should take the files from https://github.com/wet-boew/GCWeb/releases/tag/v9.1.0 and store them locally. 

Same issue as https://github.com/asc-csa/AlouetteApp/issues/61

**Comment by emilinecsa** [comment]
The latest version of the SCISAT micro applications was deployed on the production server on April 13th. I will close this bug because I can no longer replicate this issue.
