### ISSUE TITLE
Callback System uses global variables

### ISSUE THREAD

**Issue by davidreneuw** [asc-csa/Scisat-App#85]
The use of global variables in a callbackable application is deeply frowned upon because a user updating global variables may affect another users settings.

Currently, global variables are used in order to allow for a middle step (validation) between inputting values and running the controller. An alternative to this would be to use the State options that Dash offers, and make it so that the controller cannot be run if there are open alerts, therefore completely removing the global variables.

**Comment by nfee006** [comment]
FYI @coleweusthem in case this is relevant to you. https://dash.plotly.com/sharing-data-between-callbacks

**Comment by coleweusthem** [comment]
@nfee006, thanks for the heads up. I don't think this should affect the work I've done thus far.

**Comment by nfee006** [comment]
@dreneuw is this fixed?

**Comment by dreneuw** [comment]
Yes, this was fixed with #87 and will be closed automatically when #87 closes
