### ISSUE TITLE
Refreshing page does not necessarily reset the data being displayed

### ISSUE THREAD

**Issue by nfee006** [asc-csa/Scisat-App#90]
This is potentially related to #85. Further details are available in #88 

To replicate: 

1. Restart app-launcher
2. Select a gas other than ozone in the gas dropdown menu.
3. Click update.
4. Refresh the page.
5. Dropdown defaults to ozone. Data displayed is actually from the gas that was selected prior to the page refresh. 
 
This should be addressed by #85 but we will need to verify.

**Comment by nfee006** [comment]
@dreneuw: is this fixed?

**Comment by dreneuw** [comment]
I am 99% certain that this is related to #85 and is resolved by it. Will need to test.

**Comment by emilinecsa** [comment]
I confirm; this issue is now fixed using the latest version of SCISAT that was deployed on the production server on April 13th.
